create database project;
use project;

CREATE TABLE professors (
	id INT AUTO_INCREMENT PRIMARY KEY,
    prof_first_name VARCHAR(255) NOT NULL,
    prof_last_name VARCHAR(255) NOT NULL
);


CREATE TABLE sections (
	id INT AUTO_INCREMENT PRIMARY KEY,
    subject VARCHAR(255) NOT NULL,
    prof_id INT,
    FOREIGN KEY (prof_id)
        REFERENCES professors(id)
);

CREATE TABLE students (
	id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    section_id INT,
    FOREIGN KEY (section_id)
        REFERENCES sections(id)
);


CREATE TABLE activities (
	id INT AUTO_INCREMENT PRIMARY KEY,
    activity_name VARCHAR(255) NOT NULL,
    activity_grade INT,
    student_id INT,
    section_id INT,
    FOREIGN KEY (student_id)
        REFERENCES students(id),
	FOREIGN KEY (section_id)
		REFERENCES sections(id)
);

INSERT INTO students(first_name,last_name)
VALUES
	('Harper', 'Garza'),
	('Stephen', 'Mcfadden'),
	('Kareem', 'Keith'),
	('Uma', 'Mills'),
	('Lana', 'Brady'),
	('Hall', 'Delacruz'),
	('Linda', 'Payne'),
	('Chloe', 'Stokes'),
	('Heather', 'Rogers'),
	('Jason', 'Flowers'),
	('Timon', 'Hayden'),
	('Bree', 'Tran'),
	('Rudyard', 'Monroe'),
	('Wylie', 'Oneill'),
	('Quinn', 'Miles'),
	('Kitra', 'Lee'),
	('Xyla', 'Hutchinson'),
	('Kadeem', 'Carver'),
	('Ishmael', 'Welch'),
	('Lee', 'Sanford'),
	('Allegra', 'Warren'),
	('Elaine', 'Hess'),
	('Channing', 'Blackwell'),
	('Zachery', 'Sargent'),
	('Baker', 'Park'),
	('Alyssa', 'Hicks'),
	('Dakota', 'Hooper'),
	('Clio', 'Roth'),
	('Mannix', 'Wilkins'),
	('Laurel', 'Cummings'),
	('Jocelyn', 'Delacruz'),
	('Jordan', 'Brewer'),
	('Ariel', 'Larsen'),
	('Ingrid', 'Jenkins'),
	('Alice', 'Webster'),
	('Macey', 'Savage'),
	('Daria', 'Snow'),
	('Hilda', 'Woods'),
	('Kalia', 'Young'),
	('Gail', 'Irwin'),
	('Kibo', 'Golden'),
	('Carla', 'Dudley'),
	('Logan', 'Sanders'),
	('Harper', 'Haley'),
	('Kelly', 'Ellis'),
	('Ann', 'Santiago'),
	('Ronan', 'Whitney'),
	('Shelly', 'Mcclain'),
	('Indira', 'Mcgee'),
	('Lars', 'Buchanan'),
	('Lev', 'Malone'),
	('Xaviera', 'Stanton'),
	('Vladimir', 'Burks'),
	('Ann', 'Love'),
	('Daryl', 'Freeman'),
	('Palmer', 'Lott'),
	('Gisela', 'Fernandez'),
	('Aretha', 'Rodgers'),
	('Ori', 'Meadows'),
	('Macy', 'Lambert'),
	('Ursa', 'Summers'),
	('Xander', 'Rivers'),
	('Noelle', 'Whitehead'),
	('Josephine', 'Kennedy'),
	('Clare', 'Burch'),
	('Abraham', 'Delacruz'),
	('Serina', 'Yates'),
	('Oprah', 'Delaney'),
	('Gay', 'Sargent'),
	('Lewis', 'Hubbard'),
	('Jonah', 'Pena'),
	('Dillon', 'Guy'),
	('Courtney', 'Hoover'),
	('Casey', 'Suarez'),
	('Amela', 'Blackwell'),
	('Barry', 'Curry'),
	('Warren', 'Marshall'),
	('Aidan', 'Glover'),
	('Garth', 'Melendez'),
	('Imani', 'Mckenzie'),
	('Alexis', 'Romero'),
	('Rebecca', 'Bryant'),
	('Zenaida', 'Terrell'),
	('Lydia', 'Vinson'),
	('Nigel', 'Bentley'),
	('Nicholas', 'Thornton'),
	('Lewis', 'Graves'),
	('Carson', 'Mack'),
	('Kiara', 'Mendoza'),
	('Zoe', 'Franks'),
	('Lucy', 'Harding'),
	('Phillip', 'Cantu'),
	('Lacy', 'Downs'),
	('Yuli', 'Ratliff'),
	('Grant', 'Aguirre'),
	('Aretha', 'Wilkinson'),
	('Eagan', 'Doyle'),
	('Rhiannon', 'Hurley'),
	('Maisie', 'Kaufman'),
	('Wang', 'Mason')
;

INSERT INTO sections(subject)
VALUES
	('Theology'),
	('Physical Education'),
	('English Communication'),
	('General Chemistry'),
	('College Algebra'),
	('Trigonometry'),
	('Differential Calculus'),
	('Panitikang Filipino'),
	('Politics and Government'),
	('Physics'),
	('Discrete Mathematics'),
	('Logic Circuits'),
	('Computer Programming'),
	('Electrical Circuits'),
	('Object Oriented Programming'),
	('Engineering Economy'),
	('Static of Rigid Bodies'),
	('Differential Equations'),
	('Nihongo'),
	('World Literature'),
	('Integral Calculus'),
	('Dynamics of Rigid Bodies'),
	('Mechanics of Deformable Bodies'),
	('General Psychology'),
	('Software Engineering')
;

INSERT INTO professors(prof_first_name, prof_last_name)
VALUES
	('Alejandro', 'Campbell'),
	('Youssef', 'Forster'),
	('Emmie', 'Berry'),
	('Aanya', 'Iles'),
	('Marnie', 'Roche'),
	('Arandeep', 'Patton'),
	('Jevan', 'Morton'),
	('Jane', 'Adam'),
	('Krystian', 'Gallagher'),
	('Gurpreet', 'Pratt'),
	('Maisey', 'Delgado'),
	('Clodagh', 'Bass'),
	('Elspeth', 'Yu'),
	('Gurdeep', 'Valenzuela'),
	('Josef', 'Neil')
;

INSERT INTO activities(activity_name, activity_grade)
VALUES
	('Recitation', 85),
	('Recitation', 95),
	('Recitation', 76),
	('Recitation', 69),
	('Recitation', 72),
	('Recitation', 92),
	('Recitation', 0),
	('Recitation', 56),
	('Recitation', 89),
	('Recitation', 71),
	('Recitation', 56),
	('Recitation', 91),
	('Recitation', 86),
	('Recitation', 66),
	('Recitation', 82),
	('Recitation', 70),
	('Recitation', 90),
	('Recitation', 67),
	('Recitation', 75),
	('Recitation', 85),
	('Boardwork', 91),
	('Boardwork', 82),
	('Boardwork', 73),
	('Boardwork', 83),
	('Boardwork', 92),
	('Boardwork', 71),
	('Boardwork', 56),
	('Boardwork', 77),
	('Boardwork', 94),
	('Boardwork', 0),
	('Boardwork', 50),
	('Boardwork', 88),
	('Boardwork', 12),
	('Boardwork', 65),
	('Boardwork', 74),
	('Boardwork', 47),
	('Boardwork', 95),
	('Boardwork', 76),
	('Boardwork', 88),
	('Boardwork', 90),
	('Seatwork', 90),
	('Seatwork', 85),
	('Seatwork', 74),
	('Seatwork', 85),
	('Seatwork', 96),
	('Seatwork', 77),
	('Seatwork', 54),
	('Seatwork', 62),
	('Seatwork', 96),
	('Seatwork', 69),
	('Seatwork', 74),
	('Seatwork', 67),
	('Seatwork', 59),
	('Seatwork', 35),
	('Seatwork', 0),
	('Seatwork', 79),
	('Seatwork', 71),
	('Seatwork', 80),
	('Seatwork', 99),
	('Seatwork', 84),
	('Homework', 100),
	('Homework', 95),
	('Homework', 90),
	('Homework', 96),
	('Homework', 86),
	('Homework', 93),
	('Homework', 0),
	('Homework', 86),
	('Homework', 76),
	('Homework', 86),
	('Homework', 95),
	('Homework', 72),
	('Homework', 70),
	('Homework', 80),
	('Homework', 90),
	('Homework', 86),
	('Homework', 81),
	('Homework', 94),
	('Homework', 72),
	('Homework', 83),
	('Project', 60),
	('Project', 75),
	('Project', 85),
	('Project', 95),
	('Project', 65),
	('Project', 88),
	('Project', 92),
	('Project', 76),
	('Project', 0),
	('Project', 67),
	('Project', 97),
	('Project', 81),
	('Project', 80),
	('Project', 70),
	('Project', 90),
	('Project', 69),
	('Project', 66),
	('Project', 81),
	('Project', 87),
	('Project', 0),
	('Quiz', 47),
	('Quiz', 56),
	('Quiz', 87),
	('Quiz', 78),
	('Quiz', 15),
	('Quiz', 65),
	('Quiz', 45),
	('Quiz', 35),
	('Quiz', 78),
	('Quiz', 65),
	('Quiz', 72),
	('Quiz', 69),
	('Quiz', 49),
	('Quiz', 55),
	('Quiz', 75),
	('Quiz', 76),
	('Quiz', 36),
	('Quiz', 90),
	('Quiz', 62),
	('Quiz', 68),
	('Exam', 75),
	('Exam', 62),
	('Exam', 81),
	('Exam', 75),
	('Exam', 62),
	('Exam', 34),
	('Exam', 56),
	('Exam', 30),
	('Exam', 29),
	('Exam', 45),
	('Exam', 91),
	('Exam', 72),
	('Exam', 80),
	('Exam', 73),
	('Exam', 64),
	('Exam', 90),
	('Exam', 79),
	('Exam', 27),
	('Exam', 61),
	('Exam', 100)
;

select * from students;
select * from professors;
select * from sections;
select * from activities;